django_crm/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "django_crm"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path("", views.home, name="home"),
    # path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
    path("record/<int:pk>", views.customer_record, name="record"),
    path("delete_record/<int:pk>", views.delete_record, name="delete_record"),
    path("update_record/<int:pk>", views.update_record, name="update_record"),
    path("add_record", views.add_record, name="add_record"),
]

website/models.py
from django.db import models

# Create your models here.
class Record(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    address = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=9)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    zipcode = models.CharField(max_length=10)

    def __str__(self) -> str:
        return(f"{self.first_name} {self.last_name}")
    

website/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms

from .models import Record

class SignupForm(UserCreationForm):
    email = forms.EmailField(label="", required=True, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Email address"
    }))
    first_name = forms.CharField(label="", max_length=40, required=True, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "First name"
    }))
    last_name = forms.CharField(label="", max_length=40, required=True, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Last name"
    }))

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	

class AddRecordForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget = forms.widgets.TextInput(attrs={
        "placeholder": "First Name",
        "class": "form-control"
    }), label="")

    last_name = forms.CharField(required=True, widget = forms.widgets.TextInput(attrs={
        "placeholder": "Last Name",
        "class": "form-control"
    }), label="")

    address = forms.CharField(required=True, widget = forms.widgets.TextInput(attrs={
        "placeholder": "Address",
        "class": "form-control"
    }), label=
"")    
    email = forms.CharField(required=True, widget = forms.widgets.TextInput(attrs={
        "placeholder": "Email",
        "class": "form-control"
    }), label="")
    
    phone = forms.CharField(required=True, widget = forms.widgets.TextInput(attrs={
        "placeholder": "Phone",
        "class": "form-control"
    }), label="")
    
    city = forms.CharField(required=True, widget = forms.widgets.TextInput(attrs={
        "placeholder": "City",
        "class": "form-control"
    }), label="")
    
    state = forms.CharField(required=True, widget = forms.widgets.TextInput(attrs={
        "placeholder": "State",
        "class": "form-control"
    }), label="")
    
    zipcode = forms.CharField(required=True, widget = forms.widgets.TextInput(attrs={
        "placeholder": "Zipcode",
        "class": "form-control"
    }), label="")

    class Meta:
        model = Record
        exclude = ("user",)

website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import SignupForm, AddRecordForm
from .models import Record

# Create your views here.
def home(request):

    records = Record.objects.all()
    
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user=user)
            messages.success(request, "You are logged in!")
            return redirect("website:home")
        else:
            messages.error(request, "Error! Please try again")
            return redirect("website:home")

    else:
        return render(request, "website/home.html", {
            "records": records,
        })

def logout_user(request):
    logout(request)
    messages.success(request, "You were logged out.")
    return redirect("website:home")

def register_user(request):

    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "You are registered!")
            
            return redirect("website:home")
        
        
    else:
        form = SignupForm()
        return render(request, "website/register.html", {
            "form": form,
        })
    
    return render(request, "website/register.html", {
        "form": form,
    })

def customer_record(request, pk):
    if request.user.is_authenticated:
        customer_record = Record.objects.get(id=pk)    

        return render(request, "website/record.html", {
            "customer_record": customer_record,
        })
    
    else:
        messages.success(request, "You must be logged in to see that page...")
        return redirect("website:home")
    
def delete_record(request, pk):
    if request.user.is_authenticated:
        record = Record.objects.get(id=pk)
        record.delete()
        messages.success(request, "Record deleted successfully.")
        return redirect("website:home")
    else:
        messages.success(request, "You need to login to do this.")
        return redirect("website:home")
    
def add_record(request):

    form = AddRecordForm(request.POST or None)

    if request.user.is_authenticated:
        if request.method == "POST":
            if form.is_valid():
                add_record = form.save()
                messages.success(request, "Record added.")
                return redirect("website:home")
            
        return render(request, "website/add_record.html", {
            "form": form,
        })
    
    else:
        messages.success(request, "You need to be logged in to add record")
        return redirect("website:home")

def update_record(request, pk):
    if request.user.is_authenticated:
        current_record = Record.objects.get(id=pk)
        form = AddRecordForm(request.POST or None, instance=current_record)

        if form.is_valid():
            form.save()
            messages.success(request, "Record haas been updated")
            return redirect("website:home")
        
        return render(request, "website/update_record.html", {
            "form": form,
        })

    else:
        messages.success(request, "You need to be logged in to add record")
        return redirect("website:home")

website/templates/website/add_record.html
{% extends 'website/base.html' %}

{% block content %}

<div class="offset-md-3">

    <h1>Add Record</h1>


    <form method="post" action="{% url 'website:add_record' %}">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-secondary mt-4">Add Record</button>
        <a href="{% url 'website:home' %}" class="btn btn-secondary mt-4">Back</a>

    </form>

</div>

{% endblock %}

website/templates/website/base.html
<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Django CRM</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>

    <body>

        {% include "website/navbar.html" %}

        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>    
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock content %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>

</html>

website/templates/website/home.html
{% extends 'website/base.html' %}

{% block content %}

    {% if user.is_authenticated %}

        {% if records %}
        <div class="table-responsive-lg">
            <table class="table table-striped table-hover align-middle caption-top">
                <caption>List of customers</caption>

                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Address</th>
                        <th scope="col">City</th>
                        <th scope="col">State</th>
                        <th scope="col">Zipcode</th>
                        <th scope="col">Created at</th>
                        <th scope="col">ID</th>
                    </tr>
                </thead>
        
                <tbody class="table-group-divider">
                    {% for record in records %}
                    <tr>
                        <td><a href="{% url 'website:record' record.id%}" class="link-secondary">{{ record.first_name }} {{ record.last_name }}</a></td>
                        <td>{{ record.email }}</td>
                        <td>{{ record.phone }}</td>
                        <td>{{ record.address }}</td>
                        <td>{{ record.city }}</td>
                        <td>{{ record.state }}</td>
                        <td>{{ record.zipcode }}</td>
                        <td>{{ record.created_at }}</td>
                        <td><a href="{% url 'website:record' record.id%}" class="link-secondary">{{ record.id }}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
        
        {% else %}
            <p>No record found...</p>
        {% endif %}
    
    {% else %}  
    
    <div class="offset-md-3">
        <h1 class="mb-5">Login</h1>
    
        <form method="post" action="{% url 'website:home' %}">
            {% csrf_token %}
            <div class="mb-4">
                <label class="mb-1 ms-1" for="exampleInputEmail1" class="form-label">Username:</label>
                <input type="text" class="form-control" name="username" placeholder="Username" required>
            </div>
            <div class="mb-4">
                <label class="mb-1 ms-1" for="exampleInputPassword1" class="form-label">Password:</label>
                <input type="password" class="form-control" name="password" placeholder="Password" required>
            </div>
            <button type="submit" class="btn btn-secondary">Login</button>
        </form>        
    </div>

    {% endif %}

{% endblock content %}

website/templates/website/navbar.html
<nav class="navbar d-flex flex-row sticky-top navbar-expand-lg navbar-dark bg-dark mb-5">

    <div>
        <a class="navbar-brand mx-4" href="{% url 'website:home' %}">Django CRM</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    
    <div class="collapse navbar-collapse d-flex flex-row justify-content-end gap" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">

            {% if user.is_authenticated %}
                <li class="nav-item mx-2">
                    <a class="nav-link" href="{% url 'website:add_record' %}">Add Record</a>
                </li>
                <li class="nav-item me-4">
                    <a class="nav-link"  href="{% url 'website:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item me-3">
                    <a class="nav-link border rounded px-3 py-2" href="{% url 'website:home' %}">Login</a>
                </li>

                <li class="nav-item me-4">
                    <a class="nav-link border rounded px-3 py-2" href="{% url 'website:register' %}">Register</a>
                </li>
            {% endif %}

        </ul>
    </div>

</nav>

website/templates/website/record.html
{% extends 'website/base.html' %}
{% block content %}

<div class="card">
    <div class="card-header mt-2">
        <h5>{{ customer_record.first_name }} {{ customer_record.last_name }}</h5>
    </div>
    <div class="card-body">
        <p class="card-text">
            <strong>Email: </strong>{{ customer_record.email }} <br>
        </p>
        <p class="card-text">
            <strong>Phone: </strong>{{ customer_record.phone }} <br>
        </p>
        <p class="card-text">
            <strong>Address: </strong>{{ customer_record.address }} <br>
        </p>
        <p class="card-text">
            <strong>city: </strong>{{ customer_record.city }} <br>
        </p>
        <p class="card-text">
            <strong>State: </strong>{{ customer_record.state }} <br>
        </p>
        <p class="card-text">
            <strong>Zipcode: </strong>{{ customer_record.zipcode }} <br>
        </p>
        <p class="card-text">
            <strong>Created at: </strong>{{ customer_record.created_at }} <br>
        </p>
        <p class="card-text">
            <strong>ID: </strong>{{ customer_record.id }} <br>
        </p>
    </div>
</div>

<a href="{% url 'website:home' %}" class="btn btn-secondary mt-3">Back</a>
<a href="{% url 'website:update_record' customer_record.id%}" class="btn btn-secondary mt-3">Update</a>
<a href="{% url 'website:delete_record' customer_record.id%}" class="btn btn-danger mt-3">Delete</a>




{% endblock content %}

website/templates/website/register.html
{% extends 'website/base.html' %}

{% block content %}

<div class="col-md-6 offset-md-3">

    <h1 class="mb-5">Register</h1>


    <form method="post" action=".">
        {% csrf_token %}

        {% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			Your form has errors:
                {% for field in form %}

                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}

                {% endfor %}

                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endif %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-secondary">Register</button>

</div>

{% endblock content %}

website/templates/website/update_record.html
{% extends 'website/base.html' %}

{% block content %}

<div class="offset-md-3">

    <h1 class="mb-5">Update Record</h1>


    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-secondary mt-4">Update Record</button>

    </form>

</div>

{% endblock %}